before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: neko
    main: ./main.go
    ldflags: -s -w
    binary: ipterm
    goos:
      - darwin
      - linux
      - freebsd
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
