before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: neko
    main: ./main.go
    ldflags: -s -w
    binary: neko
    goos:
      - darwin
      - linux
      - freebsd
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
